### PR TITLE
Upgrade JaCoCo to 0.7.7 and ASM to 5.1

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by Godin** [comment]
@marchof I've used this PR to check "report-aggregate" and prepare for upgrade to JaCoCo 0.7.7. Do you think that this change in tests due jacoco/jacoco#387 might have functional consequences?

**Comment by marchof** [comment]
@Godin No, I don't think jacoco/jacoco#387 has an impact on EclEmma as exec file processing is fully handled within JaCoCo. Also this issue did not change the file format as such.

**Comment by Godin** [comment]
ready to be merged, @marchof could you please review?

**Comment by marchof** [comment]
LGTM!

**Comment by marchof** [comment]
@Godin Sorry, I didn't select squash.

**Pull request merged**
